/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findyourfilm;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author elton
 */
public class MovieFrame extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public Customer customer = null;
    public boolean child;
    public DefaultListModel movieListModel;
    public String currentDate;
    public String[][] origin;
    
    public MovieFrame(Customer user, boolean c) {
        movieListModel = new DefaultListModel();
        initComponents();
        customer = user;
        child = c;
        currentDate ="18-Nov-19";
        dateLbl.setText(currentDate);
        initMovieList(currentDate);
        
    }
    public MovieFrame(Customer user,String[][] movies)
    { DatabaseConnection db = new DatabaseConnection();
       origin = movies;
        movieListModel = new DefaultListModel();
        initComponents();
        customer = user;
        currentDate ="18-Nov-19";
        dateLbl.setText(currentDate);
        String[][] daily = db.searchDate(currentDate, movies);
       for(int i =0 ;i < daily.length;i++)
           
        {
            String movie = daily[i][0] + "|"+daily[i][1]+"|" + daily[i][2]+ "|"+ daily[i][3]+ "|"+daily[i][4]+ "|"+daily[i][5];
  
            movieListModel.addElement(movie);
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        movieList = new javax.swing.JList<>();
        purchaseTicketBtn = new javax.swing.JButton();
        viewMovieBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        rightArrowBtn = new javax.swing.JButton();
        leftArrowBtn = new javax.swing.JButton();
        dateLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 690));
        setResizable(false);

        movieList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        movieList = new javax.swing.JList<>(movieListModel);
        jScrollPane1.setViewportView(movieList);

        purchaseTicketBtn.setText("Purchase Ticket");
        purchaseTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseTicketBtnActionPerformed(evt);
            }
        });

        viewMovieBtn.setText("View Movie Bio");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        rightArrowBtn.setText(">");
        rightArrowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightArrowBtnActionPerformed(evt);
            }
        });

        leftArrowBtn.setText("<");
        leftArrowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftArrowBtnActionPerformed(evt);
            }
        });

        dateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLbl.setText("January 21 2019");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(leftArrowBtn)
                                .addGap(63, 63, 63)
                                .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rightArrowBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(purchaseTicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewMovieBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightArrowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(dateLbl)
                    .addComponent(leftArrowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseTicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewMovieBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void initMovieList(String date)
    {
        DatabaseConnection db = new DatabaseConnection();
        origin = db.movieDB;
        String[][] movies  = db.searchDate(date,db.movieDB);
       
        
        
        //movies = db
        for(int i =0 ;i < movies.length;i++)
        {
            String movie = movies[i][0] + "|"+movies[i][1]+"|" + movies[i][2]+ "|"+ movies[i][3]+ "|"+movies[i][4]+ "|"+movies[i][5];
  
            movieListModel.addElement(movie);
        }
      
       
    }
    public void refreshList()
    {
        movieListModel.clear();
         DatabaseConnection db = new DatabaseConnection();
          String[][] movies  = db.searchDate(currentDate,origin);
       
        
        
        //movies = db
        for(int i =0 ;i < movies.length;i++)
        {
            String movie = movies[i][0] + "|"+movies[i][1]+"|" + movies[i][2]+ "|"+ movies[i][3]+ "|"+movies[i][4]+ "|"+movies[i][5];
  
            movieListModel.addElement(movie);
        }
        
    }
    private void rightArrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightArrowBtnActionPerformed
        // TODO add your handling code here:
        String dayS = currentDate.substring(0, 2);
        int dayI= Integer.parseInt(dayS);
        dayI++;
        currentDate = dayI+currentDate.substring(2);
        dateLbl.setText(currentDate);
        refreshList();
        
        
        
    }//GEN-LAST:event_rightArrowBtnActionPerformed

    private void leftArrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftArrowBtnActionPerformed
        // TODO add your handling code here:
         String dayS = currentDate.substring(0, 2);
        int dayI= Integer.parseInt(dayS);
        dayI--;
        currentDate = dayI+currentDate.substring(2);
        dateLbl.setText(currentDate);
        refreshList();
        
    }//GEN-LAST:event_leftArrowBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        MainFrame MFrame = new MainFrame(customer);
        MFrame.getContentPane().setBackground(Color.white);
        MFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void purchaseTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseTicketBtnActionPerformed
        // TODO add your handling code here:
        String ticketString =  movieList.getSelectedValue();
        String[] ticketSplit = ticketString.split("\\|");
        Ticket ticket = new Ticket(ticketSplit[0],ticketSplit[1],ticketSplit[2],ticketSplit[3],ticketSplit[4],ticketSplit[5]);
        customer.AddTicket(ticket);
        customer.saveState(customer);
        System.out.println("Ticket added!"); 
    }//GEN-LAST:event_purchaseTicketBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leftArrowBtn;
    private javax.swing.JList<String> movieList;
    private javax.swing.JButton purchaseTicketBtn;
    private javax.swing.JButton rightArrowBtn;
    private javax.swing.JButton viewMovieBtn;
    // End of variables declaration//GEN-END:variables
}
