/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findyourfilm;

/**
 *
 * @author User
 */
public class advSearchFrame extends javax.swing.JFrame {

    /**
     * Creates new form advSearchFrame
     */
    public Customer customer;
    public advSearchFrame(Customer user) {
        customer = user;
        initComponents();
       
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theaterCombo = new javax.swing.JComboBox<>();
        theaterLbl = new javax.swing.JLabel();
        ratingLbl = new javax.swing.JLabel();
        ratingCombo = new javax.swing.JComboBox<>();
        typeLbl = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        theaterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Theatres", "Cineplex Yonge-Dundas", "Scotiabank Theatre", "Carlton Cinema" }));
        theaterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theaterComboActionPerformed(evt);
            }
        });

        theaterLbl.setText("Theater:");

        ratingLbl.setText("Age Rating:");

        ratingCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Ratings", "PG", "14A", "G", "R", "STC", "N/A" }));

        typeLbl.setText("Type:");

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Types", "VIP 19+", "IMAX", "Ultra AVX", "Regular", "Regular 3D", "4DX", "4DX 3D", "D-Box AVX", "Stars & Strollers" }));

        searchBtn.setText("Search!");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(theaterLbl)
                            .addComponent(ratingLbl)
                            .addComponent(typeLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(theaterCombo, 0, 1, Short.MAX_VALUE)
                            .addComponent(ratingCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(theaterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(theaterLbl))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingLbl)
                    .addComponent(ratingCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLbl)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void theaterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theaterComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_theaterComboActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        DatabaseConnection db = new DatabaseConnection();
        String[][] movies = db.movieDB;
        if(theaterCombo.getSelectedIndex()!= 0)
        movies = db.search((String) theaterCombo.getSelectedItem(),2, movies);
        if(ratingCombo.getSelectedIndex()!= 0)
        movies = db.search((String) ratingCombo.getSelectedItem(),5, movies);
        if(typeCombo.getSelectedIndex()!= 0)
        movies = db.search((String) typeCombo.getSelectedItem(),4, movies);
        new MovieFrame(customer,movies).setVisible(true);
        dispose();
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> ratingCombo;
    private javax.swing.JLabel ratingLbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> theaterCombo;
    private javax.swing.JLabel theaterLbl;
    private javax.swing.JComboBox<String> typeCombo;
    private javax.swing.JLabel typeLbl;
    // End of variables declaration//GEN-END:variables
}
