/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findyourfilm;

import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author elton
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public boolean child = false;
    public Customer customer;
    public MainFrame() {
        initComponents();
      
    }
    public MainFrame(Customer user)
    {
        customer = user;
        initComponents();
        welcomeLbl.setFont(new java.awt.Font("Yu Gothic UI", 1, 36));
        welcomeLbl.setText(("Welcome, " + user.name));
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutBtn = new javax.swing.JButton();
        quickSearchBtn = new javax.swing.JButton();
        advSearchBtn = new javax.swing.JButton();
        childModeBtn = new javax.swing.JButton();
        viewTicketsBtn = new javax.swing.JButton();
        welcomeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 690));
        setResizable(false);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        quickSearchBtn.setText("Quick Search");
        quickSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickSearchBtnActionPerformed(evt);
            }
        });

        advSearchBtn.setText("Advanced Search");
        advSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advSearchBtnActionPerformed(evt);
            }
        });

        childModeBtn.setText("Child Mode: OFF");
        childModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childModeBtnActionPerformed(evt);
            }
        });

        viewTicketsBtn.setText("View Tickets");
        viewTicketsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTicketsBtnActionPerformed(evt);
            }
        });

        welcomeLbl.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        welcomeLbl.setText("Welcome [Customer Name]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(childModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(advSearchBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                .addComponent(quickSearchBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(viewTicketsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(quickSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewTicketsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(childModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        LoginFrame LFrame = new LoginFrame();
        LFrame.getContentPane().setBackground(Color.white);
        LFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void advSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advSearchBtnActionPerformed
        // TODO add your handling code here:
        advSearchFrame advFrame = new advSearchFrame(customer);
        advFrame.getContentPane().setBackground(Color.white);
        advFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_advSearchBtnActionPerformed

    private void quickSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickSearchBtnActionPerformed
        // TODO add your handling code here:
        MovieFrame MFrame = new MovieFrame(customer,child);
        MFrame.getContentPane().setBackground(Color.white);
        MFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_quickSearchBtnActionPerformed

    private void viewTicketsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTicketsBtnActionPerformed
        // TODO add your handling code here:
        ViewTicketForm ticketForm = new ViewTicketForm(customer);
        ticketForm.getContentPane().setBackground(Color.white);
        ticketForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewTicketsBtnActionPerformed

    private void childModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childModeBtnActionPerformed
        // TODO add your handling code here:
        child = !child;
        if(child)
        {
           JOptionPane.showMessageDialog(this, "You are now in Child Mode");
            childModeBtn.setText("Child Mode: ON"); 
        } 
        else
        {
            JOptionPane.showMessageDialog(this, "You have exited Child Mode");
            childModeBtn.setText("Child Mode: OFF");
        }
            
    }//GEN-LAST:event_childModeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advSearchBtn;
    private javax.swing.JButton childModeBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton quickSearchBtn;
    private javax.swing.JButton viewTicketsBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
