/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findyourfilm;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author elton
 */
public class MovieFrame extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public Customer customer;
    public boolean child;
    public DefaultListModel movieListModel;
    public MovieFrame(Customer user, boolean c) {
        movieListModel = new DefaultListModel();
        initComponents();
        customer = user;
        child = c;
        initMovieList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        movieList = new javax.swing.JList<>();
        purchaseTicketBtn = new javax.swing.JButton();
        viewMovieBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        rightArrowBtn = new javax.swing.JButton();
        leftArrowBtn = new javax.swing.JButton();
        dateLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        movieList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        movieList = new javax.swing.JList<>(movieListModel);
        jScrollPane1.setViewportView(movieList);

        purchaseTicketBtn.setText("Purchase Ticket");

        viewMovieBtn.setText("View Movie Bio");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        rightArrowBtn.setText(">");
        rightArrowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightArrowBtnActionPerformed(evt);
            }
        });

        leftArrowBtn.setText("<");
        leftArrowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftArrowBtnActionPerformed(evt);
            }
        });

        dateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLbl.setText("January 21 2019");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewMovieBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchaseTicketBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(dateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rightArrowBtn)
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(leftArrowBtn)
                    .addContainerGap(510, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightArrowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(dateLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(purchaseTicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(viewMovieBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(leftArrowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addGap(857, 857, 857)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void initMovieList(String date)
    {
        DatabaseConnection db = new DatabaseConnection();
        String[][] movies  = db.searchDate("date",db.movieDB);
       
        
        
        //movies = db
        for(int i =0 ;i < movies.length;i++)
        {
            String movie = movies[i][0] + " "+movies[i][1]+" " + movies[i][2]+ " "+ movies[i][3]+ " "+movies[i][4]+ " "+movies[i][5];
  
            movieListModel.addElement(movie);
        }
      
       
    }
    private void rightArrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightArrowBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightArrowBtnActionPerformed

    private void leftArrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftArrowBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftArrowBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leftArrowBtn;
    private javax.swing.JList<String> movieList;
    private javax.swing.JButton purchaseTicketBtn;
    private javax.swing.JButton rightArrowBtn;
    private javax.swing.JButton viewMovieBtn;
    // End of variables declaration//GEN-END:variables
}
