/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findyourfilm;
import java.awt.Color;
/**
 *
 * @author User
 */
public class TicketInfo extends javax.swing.JFrame {

    /**
     * Creates new form TicketInfo
     */
    public Customer customer;
    
    public TicketInfo() {
        initComponents();
    }
    public TicketInfo(Customer user,Ticket ticket)
    {
        customer = user;
        initComponents();
        
        dateTxt.setText(ticket.date);
        movieNameTxt.setText(ticket.movieName);
        typeTxt.setText(ticket.movieType);
        timeTxt.setText(ticket.time);
        theaterTxt.setText(ticket.theater);
        ratingTxt.setText(ticket.rating);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieNameLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        theaterLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        movieTypeLbl = new javax.swing.JLabel();
        ratingLbl = new javax.swing.JLabel();
        dateTxt = new javax.swing.JLabel();
        movieNameTxt = new javax.swing.JLabel();
        theaterTxt = new javax.swing.JLabel();
        timeTxt = new javax.swing.JLabel();
        typeTxt = new javax.swing.JLabel();
        ratingTxt = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        barcodeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 316));
        setResizable(false);

        movieNameLbl.setText("Movie Name:");

        dateLbl.setText("Date:");

        theaterLbl.setText("Theater Name:");

        timeLbl.setText("Time:");

        movieTypeLbl.setText("Movie Type:");

        ratingLbl.setText("Rating:");

        dateTxt.setText("[Movie Date]");

        movieNameTxt.setText("[Movie Name]");

        theaterTxt.setText("[Theater Name]");

        timeTxt.setText("[Movie Time]");

        typeTxt.setText("[Movie Type]");

        ratingTxt.setText("[Movie Rating]");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        barcodeBtn.setText("View BarCode");
        barcodeBtn.setActionCommand("View Barcode");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/findyourfilm/cinema_ticket.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setSize(new java.awt.Dimension(250, 208));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timeLbl)
                            .addComponent(ratingLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(timeTxt)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ratingTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(movieNameLbl)
                                    .addComponent(theaterLbl)
                                    .addComponent(dateLbl)
                                    .addComponent(movieTypeLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movieNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(theaterTxt)
                                    .addComponent(typeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barcodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLbl)
                            .addComponent(dateTxt))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movieNameLbl)
                            .addComponent(movieNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(theaterTxt)
                            .addComponent(theaterLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movieTypeLbl)
                            .addComponent(typeTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeLbl)
                            .addComponent(timeTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ratingLbl)
                            .addComponent(ratingTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barcodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ViewTicketForm viewTicket = new ViewTicketForm(customer);
        viewTicket.getContentPane().setBackground(Color.white);
        viewTicket.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton barcodeBtn;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel dateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel movieNameLbl;
    private javax.swing.JLabel movieNameTxt;
    private javax.swing.JLabel movieTypeLbl;
    private javax.swing.JLabel ratingLbl;
    private javax.swing.JLabel ratingTxt;
    private javax.swing.JLabel theaterLbl;
    private javax.swing.JLabel theaterTxt;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JLabel timeTxt;
    private javax.swing.JLabel typeTxt;
    // End of variables declaration//GEN-END:variables
}
